from .. import utils, loader
from asyncio import sleep

@loader.tds
class ILYMod(loader.Module):
    """LoveMagicHeart теперь в Telegram!"""

    strings = {"name": "LoveMagicHeart"}

    async def lovcmd(self, message):
        """Сердечки поочерёдно"""
        await message.edit('<b>❤</b>', parse_mode= 'HTML')
        await sleep(0.25)
        await message.edit('<b>🤍</b>', parse_mode= 'HTML')
        await sleep(0.25)
        await message.edit('<b>💜</b>', parse_mode= 'HTML')
        await sleep(0.25)
        await message.edit('<b>💙</b>', parse_mode= 'HTML')
        await sleep(0.25)
        await message.edit('<b>🖤</b>', parse_mode= 'HTML')
        await sleep(0.25)
        await message.edit('<b>💚</b>', parse_mode= 'HTML')
        await sleep(0.25)
        await message.edit('<b>💛</b>', parse_mode= 'HTML')
        await sleep(0.5)
        await message.edit('<b>🧡</b>', parse_mode= 'HTML')
        await sleep(0.25)
        await message.edit('<b>❤</b>', parse_mode= 'HTML')
        await sleep(0.25)
        await message.edit('<b>🤍</b>', parse_mode= 'HTML')
        await sleep(0.25)
        await message.edit('<b>🖤</b>', parse_mode= 'HTML')
        await sleep(0.25)
        await message.edit('<b>💜</b>', parse_mode= 'HTML')
        await sleep(0.25)
        await message.edit('<b>💛</b>', parse_mode= 'HTML')
        await sleep(0.25)
        await message.edit('<b>💙</b>', parse_mode= 'HTML')
        await sleep(0.5)
        await message.edit('<b>🧡</b>', parse_mode= 'HTML')
        await sleep(0.25)
        await message.edit('<b>🤎</b>', parse_mode= 'HTML')
        await sleep(0.25)
        await message.edit('<b>💚</b>', parse_mode= 'HTML')
        await sleep(0.25)
        await message.edit('<b>❤</b>', parse_mode= 'HTML')
        await sleep(0.25)
        await message.edit('<b>💟</b>', parse_mode= 'HTML')
        await sleep(0.5)
        await message.edit('<b>💝</b>', parse_mode= 'HTML')
        await sleep(0.25)
        await message.edit('<b>💗</b>', parse_mode= 'HTML')
        await sleep(0.25)
        await message.edit('<b>💖</b>', parse_mode= 'HTML')
        await sleep(0.25)
        await message.edit('<b>🖤</b>', parse_mode= 'HTML')
        await sleep(0.25)
        await message.edit('<b>🤍</b>', parse_mode= 'HTML')
        await sleep(0.5)
        await message.edit('<b>💜</b>', parse_mode= 'HTML')
        await sleep(0.25)
        await message.edit('<b>💙</b>', parse_mode= 'HTML')
        await sleep(0.25)
        await message.edit('<b>🤎</b>', parse_mode= 'HTML')
        await sleep(0.25)
        await message.edit('<b>💟</b>', parse_mode= 'HTML')
        await sleep(0.5)
        await message.edit('<b>❤</b>', parse_mode= 'HTML')
        await sleep(0.25)
        await message.edit('<b>💜</b>', parse_mode= 'HTML')
        await sleep(0.25)
        await message.edit('<b>🧡</b>', parse_mode= 'HTML')
        await sleep(0.25)
        await message.edit('<b>💚</b>', parse_mode= 'HTML')
        await sleep(0.5)
        await message.edit('<b>💙</b>', parse_mode= 'HTML')
        await sleep(0.25)
        await message.edit('<b>🤍</b>', parse_mode= 'HTML')
        await sleep(0.25)
        await message.edit('<b>🖤</b>', parse_mode= 'HTML')
        await sleep(0.25)
        await message.edit('<b>💘</b>', parse_mode= 'HTML')
        await sleep(0.5)
        await message.edit('<b>💙</b>', parse_mode= 'HTML')
        await sleep(0.25)
        await message.edit('<b>💛</b>', parse_mode= 'HTML')
        await sleep(0.25)
        await message.edit('<b>💚</b>', parse_mode= 'HTML')
        await sleep(0.25)
        await message.edit('<b>❤</b>', parse_mode= 'HTML')
        await sleep(0.5)
        await message.edit('<b>➡️<a href="https://t.me/HACKER_PHONE_VIP">➡️💝⬅️⬅️</a></b>', parse_mode= 'HTML')



